### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by takamaka-dev** [takamaka-dev/dart_wallet_v2#1]
Scalabilita wallet per riuscire sempre a visualizzare tutti i componenti pagina e bottone più in basso che spesso viene tagliato anche dopo scroll
<img width="808" alt="Screenshot 2023-05-31 at 16 36 29" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/4e914878-c93c-486b-aceb-2c0c22cd7122">
<img width="839" alt="Screenshot 2023-05-31 at 16 36 40" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/914acc0f-eb4f-4b60-8c98-773e21b04a94">

**Comment by isacco-borsani-takamaka** [comment]
Abbiamo risolto - appena siamo pronti oggi pomeriggio rilasciamo la nuova versione completa sia del wallet che della libreria SDK!
