### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by takamaka-dev** [takamaka-dev/dart_wallet_v2#2]
Ordine dei wallet creati e' risultato random, meglio cronologico di creazione o ultimo uso/modifica
<img width="832" alt="Screenshot 2023-05-31 at 16 38 39" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/05270fb8-dc74-4b0e-a314-174dd43ecf12">

**Comment by zaikeneim** [comment]
la funziona è stata implementata facendo scorrere in cima alla lista l'ultimo wallet utilizzato

**Comment by isacco-borsani-takamaka** [comment]
Abbiamo risolto - appena siamo pronti oggi pomeriggio rilasciamo la nuova versione completa sia del wallet che della libreria SDK!
