### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by takamaka-dev** [takamaka-dev/dart_wallet_v2#3]
Cliccando bottone "Logout" mi riporta in schermata login dello stesso wallet 
<img width="921" alt="Screenshot 2023-05-31 at 16 39 27" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/a5f63f79-ad11-427c-bed7-e17ca3ce3596">
<img width="925" alt="Screenshot 2023-05-31 at 16 39 37" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/06a86136-e4af-46e8-a2e7-a33263fbe861">

Mentre io mi aspetto questa schermata dopo logout:
<img width="832" alt="Screenshot 2023-05-31 at 16 38 39" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/af35303c-cc11-49c2-92cb-002adec0b264">

**Comment by isacco-borsani-takamaka** [comment]
Abbiamo risolto - appena siamo pronti oggi pomeriggio rilasciamo la nuova versione completa sia del wallet che della libreria SDK!
