### ISSUE TITLE
Amount in PAY

### ISSUE THREAD

**Issue by takamaka-dev** [takamaka-dev/dart_wallet_v2#4]
Valore con zeri davanti che sarebbe meglio non fare scrivere a cliente:
<img width="528" alt="Screenshot 2023-05-31 at 16 43 05" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/cba091b6-d929-472f-9d9b-4f068bf3ec85">

click su spazio dove inserisco valore e automaticamente mi cancella quello inserito precedentemente:

<img width="518" alt="Screenshot 2023-05-31 at 16 43 48" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/5a7365bf-c441-4287-a40f-4092287d7e91">
<img width="414" alt="Screenshot 2023-05-31 at 16 43 58" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/931ffa87-1bca-4790-bb6d-d9b0a900ee8c">
<img width="517" alt="Screenshot 2023-05-31 at 16 44 08" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/cd5ff8c4-7e21-42a7-b217-9832e49751c6">
<img width="540" alt="Screenshot 2023-05-31 at 16 45 33" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/833f9c4c-06c4-42db-92c7-5105af4ff8b7">
<img width="504" alt="Screenshot 2023-05-31 at 16 45 40" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/c2864b60-7905-4d8a-bebc-5d98b5c559ef">
<img width="490" alt="Screenshot 2023-05-31 at 16 45 47" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/a87f3d54-7e5d-4187-afc3-ca2a1e1a7966">

**Comment by isacco-borsani-takamaka** [comment]
Abbiamo risolto - appena siamo pronti oggi pomeriggio rilasciamo la nuova versione completa sia del wallet che della libreria SDK!

p.s: l'auto delete dei campi serve ad evitare che l'utente inserisca proprio un testo "ibrido" nell'amount
