### ISSUE TITLE
Transaction Alert Text

### ISSUE THREAD

**Issue by takamaka-dev** [takamaka-dev/dart_wallet_v2#5]
Se non per developer, semplificare testo:
<img width="277" alt="Screenshot 2023-05-31 at 16 46 28" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/e9b4c35d-3798-4477-8fcf-3aa6d27ce308">

**Comment by zaikeneim** [comment]
Ora l'allert stampa solo le informazioni del costo di cpu, memory e disk
