### ISSUE TITLE
Screen Time

### ISSUE THREAD

**Issue by takamaka-dev** [takamaka-dev/dart_wallet_v2#6]
Si ferma su conferma transazione un po di secondi prima di tornare su wallet home. Scelta per rendere più smooth integrazione di transazione nel blocco e quindi visualizzazione in home?
<img width="601" alt="Screenshot 2023-05-31 at 16 47 14" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/b88fbd34-3fcd-4c03-b0ef-953c4dfaf02a">

**Comment by isacco-borsani-takamaka** [comment]
Abbiamo risolto - appena siamo pronti oggi pomeriggio rilasciamo la nuova versione completa sia del wallet che della libreria SDK!

Ridotto a 7 secondi di transizione
