### ISSUE TITLE
Size in byte

### ISSUE THREAD

**Issue by takamaka-dev** [takamaka-dev/dart_wallet_v2#7]
Come da titolo se si riesce a specificare unita' di misura
<img width="286" alt="Screenshot 2023-05-31 at 17 12 18" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/48011913-0774-4e06-bd88-6ec2c1b42d16">

**Comment by isacco-borsani-takamaka** [comment]
Abbiamo risolto - appena siamo pronti oggi pomeriggio rilasciamo la nuova versione completa sia del wallet che della libreria SDK!
