### ISSUE TITLE
Delete Button

### ISSUE THREAD

**Issue by takamaka-dev** [takamaka-dev/dart_wallet_v2#8]
Se si riesce a mettere una "x" di delete vicino a "percorso del file" in modo che se sbaglio non devo ritornare in home ma posso "cancellare" file selezionato e sceglierne un altro
<img width="709" alt="Screenshot 2023-05-31 at 17 17 28" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/0c38860b-5abf-4647-b4b8-40c40ffaba4b">

**Comment by isacco-borsani-takamaka** [comment]
Ciao Davide, è sufficiente cliccare di nuovo sul bottone "Select File" per modificarne la sorgente
