### ISSUE TITLE
Settings　Page

### ISSUE THREAD

**Issue by takamaka-dev** [takamaka-dev/dart_wallet_v2#9]
Aggiungere opzioni come:

Language
Currency
Change Password
Change Wallet Name
Notifications
etc.
<img width="909" alt="Screenshot 2023-05-31 at 17 28 02" src="https://github.com/takamaka-dev/dart_wallet_v2/assets/54283764/04667c07-432b-41e4-923a-2f5dc3daec51">

**Comment by isacco-borsani-takamaka** [comment]
Ciao Davide, 

Language e currency possono essere aggiunti ma richiedono un'estensione del wallet più articolata in quanto coinvolge il sistema di traduzioni.

Per le notifications sarà aggiunta la funzionalità con il pacchetto takamaka_core_wallet_extra 

Per quanto riguarda il change password e il change walletname non è possibile realizzarlo in quanto il nome del wallet e la password fanno parte dell'encryption del file memorizzato sul dispositivo. L'unica possibilità è effettuare una restore cambiando di fatto nome e password del wallet

**Comment by zaikeneim** [comment]
La change currency è stata implementata

**Comment by takamaka-dev** [comment]
Il sistema di traduzioni è stato implementato

**Comment by takamaka-dev** [comment]
Funzioni implementate
